services:
  postgresdb:
    image: postgres:latest
    container_name: resqueue_vaccine_postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    network_mode: host
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -h localhost -U ${DATASOURCE_USERNAME} -d ${DATASOURCE_DATABASE}",
      ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    container_name: resqueue_vaccine_app
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    depends_on:
      postgresdb:
        condition: service_healthy

volumes:
  pg_data:
