services:
  postgresdb:
    image: postgres:latest
    container_name: resqueue_pg_vaccine
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: resqueue_vaccine
    ports:
      - "5433:5432"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -h localhost -U admin -d resqueue_vaccine",
      ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pg_data_vaccine:/var/lib/postgresql/data
    networks:
      - vaccine_network

  app:
    container_name: resqueue_vaccine_app
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DATASOURCE_URL: jdbc:postgresql://localhost:5433/resqueue_vaccine
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: admin
    depends_on:
      postgresdb:
        condition: service_healthy

volumes:
  pg_data_vaccine:

networks:
  vaccine_network:
    driver: bridge
