server:
  port: 0
  forward-headers-strategy: framework

spring:
  application:
    name: resqueue-vaccine

  rabbitmq:
    host: ${RABBITMQ_HOST:jackal.rmq.cloudamqp.com}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:qfbirurm}
    password: ${RABBITMQ_PASSWORD:I8GlIzgSlp05u4YUuhcF3hU26URfTQxq}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:qfbirurm}

  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        notifications:
          destination: notifications-exchange
          contentType: application/json
          binder: rabbit
      rabbit:
        bindings:
          notifications:
            producer:
              exchange-type: topic
              routing-key: notifications
              delivery-mode: PERSISTENT

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/resqueue_vaccine}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:admin}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_BASE_ISSUER_URL:http://localhost:9000}/realms/resqueue

  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    enabled: true
    path: /vaccine/v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs
    config-url: /vaccine/v3/api-docs/swagger-config
    urls:
      - name: vaccine-service
        url: /vaccine/v3/api-docs
