name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify tag is from main branch
        run: |
          git fetch origin main
          if [ "$(git rev-list -n 1 origin/main)" != "$(git rev-list -n 1 $GITHUB_SHA)" ]; then
            echo "Tag was not created from the main branch. Exiting."
            exit 1
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_REPOSITORY }}:latest .

      - name: Push the Docker image
        run: |
          docker tag ${{ secrets.DOCKERHUB_REPOSITORY }}:latest ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
          docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.ref_name }}
